lttng-modules: update lttng adaptation layer patches
Update lttng adaptation layer patches according to the syntax required by
lttng v2.7.

This fixes errors of the form:
error: macro "LTTNG_TRACEPOINT_EVENT" passed 6 arguments, but takes just 4

JIRA: SB-7853

Signed-off-by: Abdur Rehman <abdur_rehman@mentor.com>