qtwayland: link qtwayland with dl library
when tracing is enabled qtbase need lttng which depends on dl library,
in that case qtwayland also complains  about " undefined reference to `dlsym' "
dlsym call is provided by dl library, linking qtwayland to libdl fixes
this issue.

lib dl exposes the private dl functions e.g dlopen() dlsym() that exist in libc.

JIRA: https://jira.alm.mentorg.com/browse/SB-14849

Signed-off-by: sajjad238 <sajjad_ahmed@mentor.com>